import { defineConfig } from 'oxlint'

export default defineConfig({
  jsPlugins: ['@shopify/eslint-plugin'],
  plugins: ['react', 'jsx-a11y', 'nextjs', 'typescript', 'import', 'unicorn', 'vitest'],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    perf: 'warn',
    style: 'warn',
  },
  rules: {
    '@shopify/eslint-plugin/prefer-early-return': 'error',
    'capitalized-comments': 'off',
    'eslint/arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
    'eslint/max-params': 'error',
    'eslint/no-await-in-loop': 'warn',
    'eslint/no-duplicate-imports': 'error',
    'eslint/no-else-return': 'warn',
    'eslint/no-implicit-coercion': 'error',
    'eslint/no-return-assign': 'error',
    'func-style': 'off',
    'id-length': 'off',
    'import/consistent-type-specifier-style': 'off',
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-named-export': 'off',
    'import/prefer-default-export': 'off',
    'max-statements': 'off',
    'no-continue': 'off',
    'no-magic-numbers': ['warn', { ignore: [-2, -1, 0, 1, 2, 10, 24, 60, 100, 1_000, 1_900] }],
    'no-ternary': 'off',
    'no-unassigned-import': 'off',
    'operator-assignment': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'warn',
    'prefer-exponentiation-operator': 'warn',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    'promise/prefer-await-to-callbacks': 'warn',
    'promise/prefer-await-to-then': 'warn',
    'react-hooks/exhaustive-deps': 'warn',
    'react-hooks/rules-of-hooks': 'error',
    'react-perf/jsx-no-new-array-as-prop': 'warn',
    'react-perf/jsx-no-new-function-as-prop': 'warn',
    'react-perf/jsx-no-new-object-as-prop': 'warn',
    'react/exhaustive-deps': 'error',
    'react/jsx-max-depth': ['warn', { max: 8 }],
    'react/jsx-props-no-spreading': 'off',
    'react/no-multi-comp': 'warn',
    'react/react-in-jsx-scope': 'off',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'typescript/consistent-type-definitions': ['warn', 'type'],
    'typescript/no-explicit-any': 'off',
    'typescript/no-non-null-assertion': 'warn',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/prefer-reduce-type-parameter': 'error',
    'unicorn/no-nested-ternary': 'warn',
    'unicorn/no-unreadable-array-destructuring': 'warn',
    'unicorn/prefer-array-find': 'warn',
    'unicorn/prefer-array-flat-map': 'warn',
    'unicorn/prefer-array-index-of': 'warn',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-logical-operator-over-ternary': 'error',
    'unicorn/prefer-negative-index': 'error',
    'unicorn/prefer-object-from-entries': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-set-has': 'warn',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-ternary': 'error',
    'unicorn/require-array-join-separator': 'error',
    'typescript/consistent-return': 'off',
    'unicorn/numeric-separators-style': [
      'warn',
      {
        onlyIfContainsSeparator: false,
        number: {
          minimumDigits: 4,
          groupLength: 3,
        },
      },
    ],
    'unicorn/filename-case': [
      'error',
      {
        case: 'kebabCase',
      },
    ],
    'vitest/no-importing-vitest-globals': 'off',
    'vitest/prefer-called-times': 'off',
    complexity: 'warn',
    curly: ['error', 'multi'],
    eqeqeq: ['error', 'always', { null: 'ignore' }],
  },
  ignorePatterns: [
    '.next/**',
    'node_modules/**',
    'out/**',
    'build/**',
    'dist/**',
    'coverage/**',
    'playwright-report/**',
    'test-results/**',
    'convex/_generated/**',
  ],
  overrides: [
    {
      files: ['**/*.test.*', '**/*.spec.*', 'tests/**'],
      rules: {
        'no-magic-numbers': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'vitest/prefer-to-be-truthy': 'off',
        'vitest/prefer-to-be-falsy': 'off',
      },
    },
    {
      files: ['src/backup/**/*.ts', 'src/scripts/**/*.ts'],
      rules: {
        'jest/require-hook': 'off',
      },
    },
    {
      files: ['src/**/use*-query-state.ts'],
      rules: {
        'unicorn/no-null': 'off',
      },
    },
  ],
  settings: {
    vitest: {
      typecheck: true,
    },
  },
  env: {
    builtin: true,
  },
})
