packages:
  - .

overrides:
  postcss: ^8.5.18
  sharp: ^0.35.0
  vite: 'catalog:'
  vitest: 'catalog:'

allowBuilds:
  '@clerk/shared': true
  '@vercel/speed-insights': true
  core-js: true
  esbuild: true
  oxc-resolver: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vitest: 4.1.11
  vite-plus: 0.2.4
  '@vitest/coverage-v8': 4.1.11
  '@vitest/ui': 4.1.11
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - '@tanstack/charts@0.12.0'
