import { fetchAction, fetchQuery } from 'convex/nextjs'
import { cache } from 'react'
import { api } from '~/../convex/_generated/api'
import { EMPTY_OBJECT } from '~/constants/generic'
import { type Ascent, ascentSchema } from '~/schema/ascent'
import { type TrainingSession, trainingSessionSchema } from '~/schema/training'

/**
 * Compares two objects by their date property in descending order (newest first).
 * @param a - First object with a date string property
 * @param b - Second object with a date string property
 * @returns Negative number if b is earlier than a, positive if b is later, 0 if equal
 */
const compareDates = (a: { date: string }, b: { date: string }): number =>
  new Date(b.date).getTime() - new Date(a.date).getTime()

/** ASCENTS */

/**
 * Fetches all ascents from the Convex database, validates them against the schema,
 * and returns them sorted in descending chronological order (newest first).
 * Uses React cache to prevent duplicate fetches during a single render cycle.
 * @returns Promise resolving to an array of validated ascents sorted by date (descending), or empty array on error
 */
export const getAllAscents = cache(async (): Promise<Ascent[]> => {
  'use cache'
  try {
    const ascentData = await fetchQuery(api.ascents.get, EMPTY_OBJECT)

    const parsedAscents = ascentSchema.array().safeParse(ascentData)
    if (!parsedAscents.success) {
      globalThis.console.error('Error parsing ascents from DB:', parsedAscents.error)
      return []
    }

    return parsedAscents.data.sort(compareDates)
  } catch (error) {
    globalThis.console.error('Error fetching ascents from DB:', error)
    return []
  }
})

/**
 * Adds a new ascent to the Convex database.
 * @param ascent - The ascent data to add (without _id as it's generated by the database)
 * @throws Error if the database operation fails
 */
export async function addAscent(ascent: Omit<Ascent, '_id'>): Promise<void> {
  try {
    await fetchAction(api.ascents.postAction, ascent)
  } catch (error) {
    globalThis.console.error('Error adding ascent to DB:', error)
    throw error
  }
}

/** TRAINING SESSIONS */

/**
 * Fetches all training sessions from the Convex database, validates them against the schema,
 * and returns them sorted in descending chronological order (newest first).
 * Uses React cache to prevent duplicate fetches during a single render cycle.
 * @returns Promise resolving to an array of validated training sessions sorted by date (descending), or empty array on error
 */
export const getAllTrainingSessions = cache(async (): Promise<TrainingSession[]> => {
  'use cache'
  try {
    const trainingData = await fetchQuery(api.training.get, EMPTY_OBJECT)
    const parsedTraining = trainingSessionSchema.array().safeParse(trainingData)
    if (!parsedTraining.success) {
      globalThis.console.error('Error parsing training sessions from DB:', parsedTraining.error)
      return []
    }
    return parsedTraining.data.sort(compareDates)
  } catch (error) {
    globalThis.console.error('Error fetching training sessions from DB:', error)
    return []
  }
})

/**
 * Adds a new training session to the Convex database.
 * @param session - The training session data to add (without _id as it's generated by the database)
 * @throws Error if the database operation fails
 */
export async function addTrainingSession(session: Omit<TrainingSession, '_id'>): Promise<void> {
  try {
    await fetchAction(api.training.postAction, session)
  } catch (error) {
    globalThis.console.error('Error adding training session to DB:', error)
    throw error
  }
}
