import { fetchAction, fetchQuery } from 'convex/nextjs'
import { cache } from 'react'
import { api } from '~/../convex/_generated/api'
import { EMPTY_OBJECT } from '~/constants/generic'
import { syntheticAscents, syntheticTrainingSessions } from '~/data/synthetic-climbing-data'
import type { AscentRecord } from '~/domain/canonical/ascent'
import {
  toCanonicalAscentRecord,
  toCanonicalTrainingSessionRecord,
} from '~/domain/canonical/legacy-transformers'
import type { TrainingSessionRecord } from '~/domain/canonical/training-session'
import { type LegacyAscent, ascentSchema } from '~/schema/ascent'
import { type LegacyTrainingSession, trainingSessionSchema } from '~/schema/training'
import { assertRemoteWritesEnabled, getDataSource } from './data-source'

/**
 * Compares two objects by their date property in descending order (newest first).
 * @param a - First object with a date string property
 * @param b - Second object with a date string property
 * @returns Negative number if b is earlier than a, positive if b is later, 0 if equal
 */
const compareDates = (a: { date: string }, b: { date: string }): number =>
  new Date(b.date).getTime() - new Date(a.date).getTime()

/** ASCENTS */

/**
 * Fetches all ascents from the Convex database, validates them against the schema,
 * and returns them sorted in descending chronological order (newest first).
 * Uses React cache to prevent duplicate fetches during a single render cycle.
 * @returns Promise resolving to an array of validated ascents sorted by date (descending), or empty array on error
 */
export const getAllLegacyAscents = cache(async (): Promise<LegacyAscent[]> => {
  'use cache'
  try {
    const ascentData =
      getDataSource() === 'synthetic'
        ? syntheticAscents
        : await fetchQuery(api.ascents.get, EMPTY_OBJECT)

    const parsedAscents = ascentSchema.array().safeParse(ascentData)
    if (!parsedAscents.success) {
      globalThis.console.error('Error parsing ascents from DB:', parsedAscents.error)
      return []
    }

    return parsedAscents.data.toSorted(compareDates)
  } catch (error) {
    globalThis.console.error('Error fetching ascents from DB:', error)
    return []
  }
})

export const getAllAscents = cache(async (): Promise<AscentRecord[]> => {
  'use cache'
  const legacyAscents = await getAllLegacyAscents()
  return legacyAscents.map(toCanonicalAscentRecord)
})

/**
 * Adds a new ascent to the Convex database.
 * @param ascent - The ascent data to add (without _id as it's generated by the database)
 * @throws Error if the database operation fails
 */
export async function addAscent(ascent: Omit<LegacyAscent, '_id'>): Promise<void> {
  assertRemoteWritesEnabled()

  try {
    await fetchAction(api.ascents.postAction, ascent)
  } catch (error) {
    globalThis.console.error('Error adding ascent to DB:', error)
    throw error
  }
}

/** TRAINING SESSIONS */

/**
 * Fetches all training sessions from the Convex database, validates them against the schema,
 * and returns them sorted in descending chronological order (newest first).
 * Uses React cache to prevent duplicate fetches during a single render cycle.
 * @returns Promise resolving to an array of validated training sessions sorted by date (descending), or empty array on error
 */
export const getAllLegacyTrainingSessions = cache(async (): Promise<LegacyTrainingSession[]> => {
  'use cache'
  try {
    const trainingData =
      getDataSource() === 'synthetic'
        ? syntheticTrainingSessions
        : await fetchQuery(api.training.get, EMPTY_OBJECT)
    const parsedTraining = trainingSessionSchema.array().safeParse(trainingData)
    if (!parsedTraining.success) {
      globalThis.console.error('Error parsing training sessions from DB:', parsedTraining.error)
      return []
    }
    return parsedTraining.data.toSorted(compareDates)
  } catch (error) {
    globalThis.console.error('Error fetching training sessions from DB:', error)
    return []
  }
})

export const getAllTrainingSessions = cache(async (): Promise<TrainingSessionRecord[]> => {
  'use cache'
  const legacyTrainingSessions = await getAllLegacyTrainingSessions()
  return legacyTrainingSessions.map(toCanonicalTrainingSessionRecord)
})

/**
 * Adds a new training session to the Convex database.
 * @param session - The training session data to add (without _id as it's generated by the database)
 * @throws Error if the database operation fails
 */
export async function addTrainingSession(
  session: Omit<LegacyTrainingSession, '_id'>,
): Promise<void> {
  assertRemoteWritesEnabled()

  try {
    await fetchAction(api.training.postAction, session)
  } catch (error) {
    globalThis.console.error('Error adding training session to DB:', error)
    throw error
  }
}
