"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _loading_page from './loading-page.bones.json'
import _loading_dashboard from './loading-dashboard.bones.json'
import _loading_form from './loading-form.bones.json'
import _loading_list from './loading-list.bones.json'
import _loading_compact from './loading-compact.bones.json'

configureBoneyard({"color":"var(--surface-3)","darkColor":"var(--surface-3)","animate":"shimmer","shimmerColor":"var(--surface-4)","darkShimmerColor":"var(--surface-4)","speed":"1.8s","transition":200})

registerBones({
  "loading-page": _loading_page,
  "loading-dashboard": _loading_dashboard,
  "loading-form": _loading_form,
  "loading-list": _loading_list,
  "loading-compact": _loading_compact,
})
